[radius]
enabled=false
[http]
port=8080
addr="127.0.0.1"
[huawei]
port=50100
version=2
secret="syler"
nas_port=50100
timeout=30
domain="syler"
[basic]
callback_logout="http://localhost/test"
remote_ip_as_user_ip=true
nas_ip=""
logfile="./syler.log"